### PR TITLE
Fix/unify python venv

### LINKED ISSUE #3: Random issues happen when newer Python versions are used
I'm getting multiple issues with TensorFlow and certain things compiling, and believe it wouldn't happen if I just had the tested Python 3.11. I think since we're creating a venv anyway, it should be used no matter what to keep things universal and do what is tried and true.

### PR DESCRIPTION
**Pull request by zinsy23**
## Description
Added more unified python virtual environment support for consistent environments where things are less likely to break while trying to use it. Also added much easier setup procedures for custom trigger phrases and using GPU acceleration for both transcribing text during utterances, and when training custom trigger phrases. Custom trigger phrases are now easier than ever to create using OpenWakeWord, adapted from how OVOS uses it, and GPU acceleration should be easy to do, assuming it works for everyone (tested on my RTX 3060 and all works out of the box with this setup).

### CODE REVIEW

File: dev_setup.sh [hunk 1]
```diff
@@ -201,6 +201,73 @@ find_available_python_versions() {
...
+        return 0
+    fi
+    
+    # Check for python3.10 (fallback)
+    if command -v python3.10 &> /dev/null; then
+        PYTHON_CMD="python3.10"
+        PYTHON_VERSION="3.10"
+        PYTHON_MAJOR="3"
+        PYTHON_MINOR="10"
+        echo "✅ Found Python 3.10"
```
Comment (zinsy23) [inline dev_setup.sh:229]: is this hard coded python logic best?

Comment (zinsy23) [reply dev_setup.sh:229]: Actually after reading more, I see UV is used and likely is meant to unify the environment that is known to work. Good job!

File: dev_setup.sh [hunk 2]
```diff
@@ -587,35 +658,45 @@ else
...
+    echo "  - Isolated: Doesn't interfere with system Python"
     echo ""
-    read -p "Install Python 3.11 via DeadSnakes PPA? [Y/n] (default: yes): " -r deadsnakes_ppa
-    DEADSNAKES_PPA=${deadsnakes_ppa:-Y}
     
-    if [[ "$DEADSNAKES_PPA" =~ ^[Yy]$ ]]; then
-        echo "✅ Will install Python 3.11 via DeadSnakes PPA"
-        INSTALL_DEADSNAKES=true
+    read -p "Install Python 3.11 via uv? [Y/n] (default: yes): " -r install_python
+    INSTALL_PYTHON=${install_python:-Y}
```
Comment (zinsy23) [inline dev_setup.sh:707]: Is uv more universal than deadsnakes and reputable?

File: dev_setup.sh [hunk 3]
```diff
@@ -637,57 +718,129 @@ if [[ "$EXISTING_VENV" == true && "$NEEDS_UPDATE" == false ]]; then
...
 
 # Verify Python version stability before venv creation
 echo "Verifying Python version stability before virtual environment creation..."
 if ! verify_python_version_stability "$PYTHON_CMD" 2; then
     echo "⚠️  Python version stability check failed!"
     
-    # If this is Python 3.11 and DeadSnakes was requested, try to upgrade
-    if [[ "$PYTHON_VERSION" == "3.11" && "$INSTALL_DEADSNAKES" == true ]]; then
+    # If this is Python 3.11 and we just installed it via uv, it should be stable
+    if [[ "$PYTHON_VERSION" == "3.11" && "$INSTALL_PYTHON_VIA_UV" == true ]]; then
```
Comment (zinsy23) [inline dev_setup.sh:1076]: I trust all this logic is tested?

File: dev_setup.sh [hunk 4]
```diff
@@ -1128,22 +1137,38 @@ PYTHON_MINOR=$(echo "$PYTHON_VERSION" | cut -d. -f2)
...
-    echo "Attempting to install system PyAudio package first..."
     
-    if [[ "$OS_NAME" == "debian" || "$OS_NAME" == "ubuntu" || "$OS_LIKE" == *"debian"* ]]; then
-        # Try to install system PyAudio for this Python version
-        PYTHON_DEV_PKG="python$PYTHON_VERSION-dev"
-        echo "Installing $PYTHON_DEV_PKG for PyAudio compilation..."
-        sudo apt-get install -y "$PYTHON_DEV_PKG" || echo "⚠️  $PYTHON_DEV_PKG not available"
+    # Skip Python dev package installation if using uv (already has complete headers)
+    if [[ "$INSTALL_PYTHON_VIA_UV" == true ]]; then
+        echo "ℹ️  Using uv-provided Python 3.11 - has complete headers for PyAudio compilation"
```
Comment (zinsy23) [inline dev_setup.sh:1379]: This is actually a good pattern if we want to understand how things used to be implemented and are no longer there. Good non invasive pattern showing how things changed over time.

File: requirements/requirements-offline.txt [hunk 5]
```diff
@@ -11,7 +11,10 @@ requests-futures==0.9.5
 # Audio processing
 PyAudio==0.2.11
 SpeechRecognition==3.8.1
-pocketsphinx==0.1.0
+# pocketsphinx==0.1.0  # Optional: Only needed for pocketsphinx wake word engine
+                       # Fails on x86_64 with GCC 13+ (C23 bool typedef issue)
```
Comment (zinsy23) [inline requirements/requirements-offline.txt:15]: pocketsphinx is no longer used?

File: README.md [hunk 6]
```diff
@@ -20,6 +20,11 @@
 - **Service Readiness**: Enclosure service timeout resolved
 - **Dependencies**: Local alternatives for all external services
 
+### ℹ️ **Known Installation Notes:**
+- **Pocketsphinx**: May fail on x86_64 with modern GCC (C23 issue) - this is OK, Precise wake word engine is used instead
```
Comment (zinsy23) [inline README.md:24]: I see, Pocketsphinx is installed, but some systems fail to install it? Elaborate. Looks like there's handling around it?

File: README.md [hunk 7]
```diff
@@ -362,6 +372,110 @@ tail -f /var/log/mycroft/skills.log
...
+#### **2. Pocketsphinx (Fallback)** ⚠️
+- **Status**: Optional, may fail on modern x86_64 systems
+- **Quality**: Fair accuracy, higher false positive rate
+- **Known Issue**: Fails to compile on x86_64 with GCC 13+ (C23 `bool` typedef conflict)
+- **Works On**: ARM/Raspberry Pi systems (compiles successfully)
+- **Fallback**: Mycroft automatically falls back to pocketsphinx if Precise fails
+
+**Why pocketsphinx may fail:**
+```
+Error: 'bool' cannot be defined via 'typedef'
```
Comment (zinsy23) [inline README.md:754]: Glad to see some testing has been done. It's music to my ears, given how little testing I typically encounter these days that end up causing major problems!

File: dev_setup.sh [hunk 8]
```diff
@@ -689,7 +689,19 @@ if [[ "$PYTHON_DETECTED" -ne 0 ]]; then
     fi
 else
     echo "✅ Compatible Python found: $PYTHON_CMD (Python $PYTHON_VERSION)"
-    INSTALL_PYTHON_VIA_UV=false
+    
+    # Check if this Python is from uv (installed in uv's directory)
+    PYTHON_PATH=$(which "$PYTHON_CMD" 2>/dev/null || echo "$PYTHON_CMD")
+    PYTHON_REALPATH=$(readlink -f "$PYTHON_PATH" 2>/dev/null || echo "$PYTHON_PATH")
+    
+    if [[ "$PYTHON_PATH" == *"uv/python"* ]] || [[ "$PYTHON_PATH" == *".local/share/uv"* ]] || \
```
Comment (zinsy23) [inline dev_setup.sh:727]: I assume this other change is the result of doing further testing and adjusting accordingly?

File: dev_setup.sh [hunk 9]
```diff
@@ -1103,7 +1115,7 @@ fi
 
 # Critical dependency fix: Ensure pyxdg is installed first (required for Mycroft config)
 echo "Installing critical dependencies first..."
-pip install pyxdg>=0.27
+pip install "pyxdg>=0.27"
```
Comment (zinsy23) [inline dev_setup.sh:1342]: What changes with these quotes added?

File: dev_setup.sh [hunk 10]
```diff
@@ -1194,7 +1206,10 @@ source .venv/bin/activate
 
 # Install pocketsphinx (optional - for alternative wake word "wake up")
 echo "Attempting to install pocketsphinx (optional wake word engine)..."
-if pip install pocketsphinx==0.1.0 2>&1 | tee /tmp/pocketsphinx_install.log; then
+pip install pocketsphinx==0.1.0 2>&1 | tee /tmp/pocketsphinx_install.log
+POCKETSPHINX_EXIT_CODE=${PIPESTATUS[0]}
```
Comment (zinsy23) [inline dev_setup.sh:1439]: so this is part of how it detects when an install fails? Pretty cool actually

File: dev_setup.sh [hunk 11]
```diff
@@ -1391,6 +1406,51 @@ pip install -r requirements/extra-stt.txt || echo "Some STT extras failed, conti
 echo "Installing FasterWhisper STT plugin..."
 pip install ovos-stt-plugin-fasterwhisper
 
+# Pre-download Precise wake word model to avoid runtime download issues
```
Comment (zinsy23) [inline dev_setup.sh]: what brought on downloading the wakeword from here with precise?

File: mycroft/client/text/__main__.py [hunk 12]
```diff
@@ -62,8 +62,18 @@ def main():
         # Special signal handler allows a clean shutdown of the GUI
         signal.signal(signal.SIGINT, ctrl_c_handler)
         load_settings()
-        curses.wrapper(gui_main)
-        curses.endwin()
+        try:
+            curses.wrapper(gui_main)
```
Comment (zinsy23) [inline mycroft/client/text/__main__.py:66]: You had to modify one of the original files to handle a dependency like this?

File: mycroft/client/speech/listener.py [hunk 13]
```diff
@@ -172,7 +172,8 @@ def read(self):
 
     # TODO: Localization
     def wake_up(self, audio):
-        if self.wakeup_recognizer.found_wake_word(audio.frame_data):
+        # Handle case where wakeup_recognizer is None (e.g., stand_up_word is empty)
+        if self.wakeup_recognizer and self.wakeup_recognizer.found_wake_word(audio.frame_data):
```
Comment (zinsy23) [inline mycroft/client/speech/listener.py:176]: looks like a lot of trial and error was involved and spread out multiple commits. It's probably best to separate tasks after testing if it's possible to make clear commits for each task.

File: quick-test.sh [hunk 14]
```diff
@@ -0,0 +1,92 @@
+#!/bin/bash
+# Quick validation test for Mycroft on clean systems
+# Run this after dev_setup.sh completes
+
+echo "=== Quick Mycroft Validation Test ==="
+echo ""
+
```
Comment (zinsy23) [inline quick-test.sh]: Should this have been committed to the official repo, test files?

File: test-mycroft-startup.sh [hunk 15]
```diff
@@ -0,0 +1,58 @@
+#!/bin/bash
+# Quick test script for Mycroft first-boot and restart scenarios
+
+echo "=== Mycroft Startup Test ==="
```
Comment (zinsy23) [inline test-mycroft-startup.sh]: This is another test file

File: dev_setup.sh [hunk 16]
```diff
@@ -566,10 +566,12 @@ if [[ "$EXISTING_TENSORFLOW" == true ]]; then
 else
     echo ""
     echo "🎤 CUSTOM WAKE WORD SUPPORT:"
-    echo "TensorFlow is required if you plan to train custom wake word models."
+    echo "TensorFlow is required if you want to use OR train custom wake word models."
```
Comment (zinsy23) [inline dev_setup.sh]: So this is a fix for custom wakewords support?

File: dev_setup.sh [hunk 17]
```diff
@@ -1224,43 +1224,47 @@ fi
...
-    echo "Setting up Precise engine symlink..."
+    # Download and extract Precise 0.3.0 pre-built binary
     PRECISE_DIR="$HOME/.local/share/mycroft/precise"
-    mkdir -p "$PRECISE_DIR/precise-engine"
+    mkdir -p "$PRECISE_DIR"
     
-    # Remove any existing binary
-    rm -f "$PRECISE_DIR/precise-engine/precise-engine"
+    ARCH=$(uname -m)
+    if [[ "$ARCH" == "x86_64" ]]; then
```
Comment (zinsy23) [inline dev_setup.sh]: This is another example of what would have been nice to have in a single commit with the trial and error

File: start-mycroft.sh [hunk 18]
```diff
@@ -22,6 +22,11 @@ cd -P "$( dirname "$SOURCE" )" || exit 1 # Enter scripts folder or fail!
 DIR="$( pwd )"
 VIRTUALENV_ROOT=${VIRTUALENV_ROOT:-"${DIR}/.venv"}
 
+# Add NVIDIA library paths for GPU acceleration
+# Use system CUDA libraries first, then pip-installed ones as fallback
+NVIDIA_LIB_PATH="${VIRTUALENV_ROOT}/lib/python3.11/site-packages/nvidia"
```
Comment (zinsy23) [inline start-mycroft.sh:27]: Is it fine to hard code libraries like this?

File: mycroft/client/speech/hotword_factory.py [hunk 19]
```diff
@@ -368,6 +368,151 @@ def stop(self):
             self.runner.stop()
 
 
+class OpenWakeWordHotword(HotWordEngine):
```
Comment (zinsy23) [inline mycroft/client/speech/hotword_factory.py:371]: What was the purpose of suddenly adding openwakeword instead of precise?

File: openwakeword/oww-listen.py [hunk 20]
```diff
@@ -0,0 +1,80 @@
+#!/usr/bin/env python3
+"""
```
Comment (zinsy23) [inline openwakeword/oww-listen.py:2]: Are these adapted from the official implementation of openwakeword?

File: openwakeword/oww-duplicate-samples.py [hunk 21]
```diff
@@ -0,0 +1,179 @@
+#!/usr/bin/env python3
+"""
```
Comment (zinsy23) [inline openwakeword/oww-duplicate-samples.py:2]: What is the benefit of doing duplicates like this?

File: dev_setup.sh [hunk 22]
```diff
@@ -583,25 +583,28 @@ else
...
-        echo "     • Requires: TensorFlow installation"
+        echo "  1) OpenWakeWord (Recommended) - Train new models"
+        echo "     • Modern, lightweight ONNX models"
+        echo "     • Full training support in this environment"
+        echo "     • GPU training via PyTorch (optional)"
         echo ""
-        echo "  2) OpenWakeWord - Uses ONNX models (~50MB lighter)"
-        echo "     • Best for: Lighter weight, .onnx models"
-        echo "     • Requires: OpenWakeWord + ONNX Runtime"
+        echo "  2) Precise - Use existing .pb model files only"
```
Comment (zinsy23) [inline dev_setup.sh:591]: Why does precise only work with existing models?

File: dev_setup.sh [hunk 23]
```diff
@@ -743,33 +743,63 @@ GPU_AVAILABLE=false
...
 
 if command -v nvidia-smi >/dev/null 2>&1; then
-    # Try to get GPU info
+    # Try to get GPU info for ALL GPUs
     GPU_INFO=$(nvidia-smi --query-gpu=name,compute_cap --format=csv,noheader 2>/dev/null || echo "")
     if [ -n "$GPU_INFO" ]; then
-        # Parse first GPU (could be improved to handle multiple GPUs)
-        GPU_NAME=$(echo "$GPU_INFO" | head -1 | cut -d',' -f1 | xargs)
-        GPU_COMPUTE_CAP=$(echo "$GPU_INFO" | head -1 | cut -d',' -f2 | xargs)
+        echo "Detected NVIDIA GPU(s):"
```
Comment (zinsy23) [inline dev_setup.sh:757]: Does this work for other GPUs?

File: dev_setup.sh [hunk 24]
```diff
@@ -1664,7 +1664,7 @@ pip install --no-deps ovos-stt-plugin-fasterwhisper==0.2.0
 if [[ "$ENABLE_STT_GPU" == true ]]; then
     echo ""
     echo "Installing NVIDIA CUDA runtime libraries for GPU acceleration..."
-    pip install nvidia-cudnn-cu12>=9.1.0 nvidia-cublas-cu12>=12.4.0 nvidia-cuda-runtime-cu12>=12.4.0
+    pip install "nvidia-cudnn-cu12>=9.1.0" "nvidia-cublas-cu12>=12.4.0" "nvidia-cuda-runtime-cu12>=12.4.0"
```
Comment (zinsy23) [inline dev_setup.sh]: Are these quotes what fix the redirection to shell with the < and > symbols?

File: dev_setup.sh [hunk 25]
```diff
@@ -1763,30 +1763,6 @@ except Exception as e:
     print("   This is OK - Mycroft will attempt to download it when starting")
 ENDPYTHON
 
-# Install Mimic TTS binary as fallback for audio service initialization
-echo "Installing Mimic TTS binary..."
```
Comment (zinsy23) [inline dev_setup.sh]: was this all the consistent logic that needed to get removed?

File: dev_setup.sh [hunk 26]
```diff
@@ -650,7 +650,7 @@ if [[ "$(uname -m)" =~ ^(arm|aarch64|armv7l).*$ ]]; then
     fi
 
     # Method 5: Check /proc/cpuinfo for Broadcom/Pi indicators
-    if [[ -f "/proc/cpuinfo" ]] && $(grep -c "BCM\|Raspberry Pi\|Broadcom" /proc/cpuinfo 2>/dev/null) -gt 0; then
+    if [[ -f "/proc/cpuinfo" ]] && [[ $(grep -c "BCM\|Raspberry Pi\|Broadcom" /proc/cpuinfo 2>/dev/null) -gt 0 ]]; then
```
Comment (zinsy23) [inline dev_setup.sh:653]: Was this a syntax error?

File: OPENWAKEWORD_SETUP.md [hunk 27]
```diff
@@ -136,9 +136,25 @@ python openwakeword/oww-listen.py <model.onnx> [--sensitivity 0.5]
 ### oww-train-model.py
 Main training script for OpenWakeWord models.
 
+**Interactive Mode:** Run without arguments to be prompted for all settings:
```
Comment (zinsy23) [inline OPENWAKEWORD_SETUP.md:142]: Good call here doing an interactive mode for this so it's easier to use

File: dev_setup.sh [hunk 28]
```diff
@@ -1440,6 +1440,93 @@ elif [[ "$INSTALL_OPENWAKEWORD" == true ]]; then
...
+
+        echo ""
+        echo "📦 Installing PyTorch and training dependencies..."
+        echo "   This may take several minutes (~4-6 GB download)..."
+        echo ""
+
+        # Install PyTorch with CUDA support if GPU available
+        if [[ "$GPU_AVAILABLE" == true ]]; then
+            echo "1️⃣  Installing PyTorch with CUDA 12.4 support..."
+            pip install torch==2.6.0+cu124 torchvision==0.21.0+cu124 torchaudio==2.6.0+cu124 --index-url https://download.pytorch.org/whl/cu124
```
Comment (zinsy23) [inline dev_setup.sh:1540]: Is this intended for conditionally preloading training dependencies?

File: dev_setup.sh [hunk 29]
```diff
@@ -863,6 +863,47 @@ else
     ENABLE_STT_GPU=false
 fi
 
+# Question 5: Training Dependencies (only if OpenWakeWord selected)
+INSTALL_OWW_TRAINING=false
```
Comment (zinsy23) [inline dev_setup.sh:867]: How was this not up front already?

File: dev_setup.sh [hunk 30]
```diff
@@ -1554,7 +1554,7 @@ elif [[ "$INSTALL_OPENWAKEWORD" == true ]]; then
         # Install audio processing libraries (with correct numpy version)
         echo ""
         echo "2️⃣  Installing audio processing libraries..."
-        pip install scipy==1.17.0 tqdm==4.67.2 torchinfo==1.8.0 torchmetrics==1.8.2 soundfile==0.13.1 librosa==0.11.0
+        pip install scipy==1.16.2 tqdm==4.67.2 torchinfo==1.8.0 torchmetrics==1.8.2 soundfile==0.13.1 librosa==0.11.0
```
Comment (zinsy23) [inline dev_setup.sh]: Sounds like you went through a lot of dependency hell to get things working here. Glad you put in the work! Do you think everything has been addressed overall?

File: dev_setup.sh (hunk 2 above)
Comment (zinsy23) [reply dev_setup.sh:707]: Yes. Deadsnakes is specific to Ubuntu to get different versions of python for virtual environments. And it requires compilation, which can be slow on some systems, like a Raspberry Pi. This is far more universal, and yes, it's known to be pretty widely used, and it's precompiled so installation is very fast! Works with Python 3.8 or newer for virtual environments. It makes a huge improvement in setup speeds for the virtual environment.

File: dev_setup.sh (hunk 3 above)
Comment (zinsy23) [reply dev_setup.sh:1076]: Yes, have tested on quite a few environments, and it all works there.

File: requirements/requirements-offline.txt (hunk 5 above)
Comment (zinsy23) [reply requirements/requirements-offline.txt:15]: It is. It just has compilation issues on certain systems, and generally it isn't used much anymore. In fact, it's been officially deprecated. It installs where it works, otherwise, it gracefully fails and gets ignored.

File: README.md (hunk 6 above)
Comment (zinsy23) [reply README.md:24]: See above

File: dev_setup.sh (hunk 8 above)
Comment (zinsy23) [reply dev_setup.sh:727]: Yes. Doing consistent testing across select environments to ensure quality control.

File: dev_setup.sh (hunk 9 above)
Comment (zinsy23) [reply dev_setup.sh:1342]: The > is interpreted by the system shell and can cause redirection and cause everything after it here to be ignored. Putting in quotes ensures pip gets the symbol and not the shell.

File: dev_setup.sh (hunk 10 above)
Comment (zinsy23) [reply dev_setup.sh:1439]: Yes, a lot of logs are checked against conditionals during the setup and then things are handled more gracefully throughout various types of setups and conditions.

File: dev_setup.sh (hunk 11 above)
Comment (zinsy23) [reply dev_setup.sh]: It kept overriding and causing issues with precise versioning, so taking care of it here and pointing things to the right direction fixed it and caused it to finally honor the usage in the proper environment.

File: mycroft/client/speech/listener.py (hunk 13 above)
Comment (zinsy23) [reply mycroft/client/speech/listener.py:176]: Yes, I tried get better at that in the last few commits. The way I have my environments set up and use commits to transfer things between environments, made this much easier to do. I realize that may have made review much harder, so I apologize about that. I've also been figuring out slightly better systems with testing across environments, which helps do this less too. If I find myself doing this behavior, it's a good cue to see if I can improve that. I will use that as a cue from now on to ensure I'm doing better practices.

File: quick-test.sh (hunk 14 above)
Comment (zinsy23) [reply quick-test.sh]: You're right. I will remove this. My apologies.

File: test-mycroft-startup.sh (hunk 15 above)
Comment (zinsy23) [reply test-mycroft-startup.sh]: Good catch, thanks.

File: mycroft/client/text/__main__.py (hunk 12 above)
Comment (zinsy23) [reply mycroft/client/text/__main__.py:66]: Yes. A lot of stuff broke when Mycroft was discontinued. This was necessary to fix it and it's been tested.

File: dev_setup.sh (hunk 16 above)
Comment (zinsy23) [reply dev_setup.sh]: Yes, didn't work otherwise.

File: start-mycroft.sh (hunk 18 above)
Comment (zinsy23) [reply start-mycroft.sh:27]: It will be ignored on other systems that don't have it, so yes. It's the way to keep things simple, following the KISS principle.

File: mycroft/client/speech/hotword_factory.py (hunk 19 above)
Comment (zinsy23) [reply mycroft/client/speech/hotword_factory.py:371]: I tried making it easier to create custom wakewords with Precise, but unfortunately well into the process, I discovered TensorFlow 1 was needed instead of 2. I assumed there were other dependencies using TF 2. And since this was about to become a maintenance nightmare no matter what, I decided not to do backward thinking, especially when I saw openwakeword has augmentation features where it can synthesize samples, which is supposed to improve reliability of triggers. When making a major change, I wanted to avoid backward thinking, but also any time we make changes to anything, there should be some new benefit to go along with it to help justify it. Using it just works so much better in my experience that I would have regretted having it any other way also. It is the way forward.

Comment (zinsy23) [reply mycroft/client/speech/hotword_factory.py:371]: Good call under the circumstances! Unfortunate path initially taken, but this is likely the most practical way to deal with it.

File: openwakeword/oww-listen.py (hunk 20 above)
Comment (zinsy23) [reply openwakeword/oww-listen.py:2]: Yes, and also trying to use the same pattern as Precise uses for creating new wakewords. The listener skill is useful for quickly testing models with live mic input, train for training it, etc. Those who have used Precise will find this very familiar.

Comment (zinsy23) [reply openwakeword/oww-listen.py:2]: That definitely helps justify a sudden system change too and makes it easier to adapt.

File: openwakeword/oww-duplicate-samples.py (hunk 21 above)
Comment (zinsy23) [reply openwakeword/oww-duplicate-samples.py:2]: When training a model, more epochs can make things worse one way or the other with the total length of positive and negative samples. This makes it easier to balance things as each epoch gets more exposure to whichever gets duplicated. If thinking of the balance of samples between positive and negative wakewords, and one of them is imbalanced, doing this may help quickly bring the teeter to a more even balance where more samples may not provide much more benefit. All of this is on a per epoch basis, so more or less epochs may not have nearly as much benefit as this would.

File: dev_setup.sh (hunk 22 above)
Comment (zinsy23) [reply dev_setup.sh:591]: See above comment on TF 1 vs 2 decision I had to make.

File: dev_setup.sh (hunk 23 above)
Comment (zinsy23) [reply dev_setup.sh:757]: If you're talking about AMD and other brands, no, I haven't tested that. I've spent so much of my limited free time on this that I can't currently justify doing that, unless people request it with issues.

Comment (zinsy23) [reply dev_setup.sh:757]: Fair enough. It would be good to test it at some point.

Comment (zinsy23) [reply dev_setup.sh:757]: Just opened issue #7 as a note to work on that at some point. Right now, it isn't the most practical and almost all GPU acceleration has NVIDIA in mind that it may not even be possible on AMD or others.

Comment (zinsy23) [reply dev_setup.sh:757]: Well, I don't know about not possible, but I know what you mean. Support within Python libraries. Some things may not work out of the box. From an engineering perspective, we could technically tweak things but then we'd have to modify official libraries, which yes, isn't practical for us to be the ones doing that.

File: dev_setup.sh (hunk 24 above)
Comment (zinsy23) [reply dev_setup.sh]: Yep. Explained that in an above comment too.

File: dev_setup.sh (hunk 25 above)
Comment (zinsy23) [reply dev_setup.sh]: Yes. All was cleanly in just that segment.

File: dev_setup.sh (hunk 26 above)
Comment (zinsy23) [reply dev_setup.sh:653]: Yes. There are multiple detection methods, and this one was subtly failing due to not being able to run on the Pi. Until this fix was applied.

File: OPENWAKEWORD_SETUP.md (hunk 27 above)
Comment (zinsy23) [reply OPENWAKEWORD_SETUP.md:142]: Yes. That makes it hard to get motivated to figure these things out. I aimed to eliminate that problem as much as possible by making it as easy and accessible to do as possible.

File: dev_setup.sh (hunk 28 above)
Comment (zinsy23) [reply dev_setup.sh:1540]: Yes. The training script should be able to handle loading them too, but preloading here is better so it doesn't have to be done on the spot later unexpectedly.

File: dev_setup.sh (hunk 29 above)
Comment (zinsy23) [reply dev_setup.sh:867]: Using AI to help and not setting bigger segments of code at the time. Thankfully testing helped me notice.

File: dev_setup.sh (hunk 30 above)
Comment (zinsy23) [reply dev_setup.sh]: Yes, did a bunch of testing with the standard setup and use cases, and it all works now out of the box.

**Review by zinsy23 — COMMENTED** [review]
Good. We should be good at this point!
